### ISSUE TITLE
Exception in comm_msg

### ISSUE THREAD

**Issue by DarylWM** [GibbsConsulting/jupyter-plotly-dash#23]
Hello. I tried to run the [simple example](https://pypi.org/project/jupyter-plotly-dash/) and got this exception:

`
[IPKernelApp] ERROR | Exception in comm_msg for 25f18d07590144fbb24eb3ccacda4741
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/jupyter_plotly_dash/nbkernel.py", line 26, in callback
    response, mimetype = app.process_view(stem, args, app_path)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/jupyter_plotly_dash/dash_wrapper.py", line 120, in process_view
    return func(args, app_path, view_name_parts)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/jupyter_plotly_dash/dash_wrapper.py", line 126, in rv_
    mFunc = self.as_dash_instance(base_pathname=app_path).locate_endpoint_function()
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/jupyter_plotly_dash/dash_wrapper.py", line 34, in as_dash_instance
    base_pathname = base_pathname)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 179, in form_dash_instance
    rd.callback(**cb)(func)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 407, in callback
    [self._fix_callback_item(x) for x in events])
TypeError: callback() takes from 2 to 4 positional arguments but 5 were given
`

Evaluating `!jupyter serverextension list` gives:

`
config dir: /home/ubuntu/anaconda3/envs/py36/etc/jupyter
    jupyter_plotly_dash.serverext  enabled 
    - Validating...
      jupyter_plotly_dash.serverext  OK
    nbserverproxy  enabled 
    - Validating...
      nbserverproxy  OK
`

**Comment by GibbsConsulting** [comment]
That looks like the recent change in Dash itself to no longer use events with callbacks.
Updating to the latest version of django-plotly-dash should resolve this - are you in a position to try this?
